# SprintLog Boot의 기본 설정 파일
# Spring Boot가 초기화 될 때 항상 이 파일을 읽는다.

spring:
  application:
    name: sprintlog-boot

  profiles:
    active: dev

  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 20MB

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics # 꼭 필요한 정보만 노출 # include 중 env는 제외해야함(db, pw, api secret key 등)
      base-path: /management # 경로도 바꿔서 숨김

  endpoint:
    health:
      show-details: always # 개발 환경에서는 always, 운영에서는 when_authorized(허가된 사람만 요청이 가능하도록)를 주고 사용한다.
  server:
    port: 9090 # Actuator 전용 포트 (방화벽 같은데에서 Actuator는 허용된 ip만 접근이 가능하도록 막음)

springdoc:
  swagger-ui:
    path: /api-docs-ui.html # UI page 경로
    tags-sorter: alpha # 태그 정렬 방식 (알파벳순)
    operations-sorter: method # 메서드 정렬 방식
    display-request-duration: true # 요청과 응답에 소요된 시간 표시
    doc-expansion: list # 문서 펼침 상태 (none, list, full)

  api-docs:
    path: /my-api # swagger가 우리 API의 정볼르 얻어오기 위해서 요청하는 url

sprintlog:
  welcome-message: "SprintLog Boot - 외부 설정 시연(기본)"
  sample-data:
    enabled: true
    count: 4
  file-directory: /Users/apple/Desktop/codeit-13th-develop/sprintlog-boot/attachfile