
name: ci

# - 트리거: 언제 이 워크플로가 도는가?
on:
  push:
    branches: [ "main" ] # main에 push되면
  pull_request:
    branches: [ "main" ] # main에 PR이 열리면
  workflow_dispatch:  # 수동 실행 버튼 (Actions 탭에서 직접)

jobs:
  # 1. 빌드 + 테스트 (CI의 핵심)
  build:
    runs-on: ubuntu-latest # Github가 빌려주는 리눅스 운영체제 러너
    steps:
      - name: 코드 체크아웃
        uses: actions/checkout@v7 # 내 github repository에서 코드를 가져오겠다.

      - name: JDK 17 설치
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: "17"

      - name: 빌드 + 테스트
        run: |
          chmod +x gradlew 
          ./gradlew build
  

  # 2. AWS 연동 테스트
  aws-connection-test:
    runs-on: ubuntu-latest
    steps:
      - name: AWS 자격증명 설정 (Github Secrets)
        uses: aws-actions/configure-aws-credentials@v6
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: 연동 확인 (내 계정/역할이 맞는지)
        run: aws sts get-caller-identity